
---
title: adventurous-ant
date: 2026-09-02
subtitle: Indonesia
acronyms:
  insert_loa: false
---

## Description and Rationale

I am an independent participant with an interest in data analysis, data science, and machine learning, particularly in their applications to aviation. I decided to register for the PRC Data Challenge to gain practical experience working with real-world aviation data and to further develop my skills in data processing, analysis, and machine learning. I am particularly interested in exploring how data-driven approaches can be applied to better understand and address challenges in the aviation domain. Through this challenge, I hope to enhance my technical skills, gain valuable experience, and learn from other participants and the wider aviation and data science community.

## Details

* Type: Independent
* Country: Indonesia

```{r echo=FALSE}
library(gt)

gt(tibble::tribble(
  ~id,   ~forename,  ~surname,  ~affiliation,
   1L, "Amirah AB", "Zubaidi", "Independent"
)
) |> cols_label(id = md("**ID**"), forename = md("**Forename**"), surname ~ md("**Surname**"), affiliation ~ md("**Affiliation**"))
```
