
---
title: daring-quilt
date: 2026-09-08
subtitle: United States
acronyms:
  insert_loa: false
---

## Description and Rationale

I’m a data and technology enthusiast with a background in statistics, data science, software engineering, and analytics, and I enjoy turning complex real-world problems into practical, data-driven solutions. I decided to take on the PRC Challenge independently because I wanted to push myself outside my comfort zone, take full ownership of the problem from start to finish, and learn through hands-on experimentation. I’m excited to explore different approaches, challenge my assumptions, strengthen my technical and problem-solving skills, and see how far I can take a solution on my own. More than anything, I joined because I genuinely enjoy learning by building, and I see this challenge as an opportunity to create something meaningful while learning from the wider community.

## Details

* Type: Independent
* Country: United States
* Number of team members: 1

```{r echo=FALSE}
library(gt)

gt(tibble::tribble(
  ~id, ~forename, ~surname,  ~affiliation,
   1L,  "Manish", "Parmar", "Independent"
)
) |> cols_label(id = md("**ID**"), forename = md("**Forename**"), surname ~ md("**Surname**"), affiliation ~ md("**Affiliation**"))
```
