
---
title: gentle-monkey
date: 2026-09-11
subtitle: India
acronyms:
  insert_loa: false
---

## Description and Rationale

I am an independent learner and software developer with an interest in machine learning, data science, and real-world ML applications. I recently completed a computer vision project for real-time industrial defect detection and am currently strengthening my foundations in machine learning and linear algebra. I decided to participate in the PRC Data Challenge 2026 to gain hands-on experience with a real-world machine learning problem, particularly regression, feature engineering, data analysis, and model evaluation. I am also interested in understanding how machine learning can be applied to improve aviation-related data analysis and prediction.

## Details

* Type: Independent
* Country: India
* Number of team members: 1

```{r echo=FALSE}
library(gt)

gt(tibble::tribble(
  ~id, ~forename, ~surname, ~affiliation,
   1L, "Krushna", "Chavan",         "NA"
)
) |> cols_label(id = md("**ID**"), forename = md("**Forename**"), surname ~ md("**Surname**"), affiliation ~ md("**Affiliation**"))
```
