---
title: Registrations et al.
listing:
  id: teams-listings
  contents: "*.qmd"
  field-display-names:
    title: "Team"
    date: "Request date"
    subtitle: "Country"
  fields: [title, subtitle, date]
#   # sort: "date desc"
  type: table
  date-format: "iso"
#   # categories: unnumbered
#   # sort-ui: false
  filter-ui: [title, subtitle, date]
#   # image-align: left
#   # image-height: 1.75in
# title-block-banner: false

format:
  html:
    toc: true
    toc-depth: 2

acronyms:
  insert_loa: false
---


```{r plot_cumul, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(conflicted)
library(tidyverse)

conflicts_prefer(dplyr::filter)

source(here::here("R", "helpers.R"))


phase1_start_25 <- as_datetime("2025-10-01T00:00:00Z")
phase1_end_25 <- as_datetime("2025-11-09T23:59:59Z")
phase2_start_25 <- as_datetime("2025-11-10T00:00:00Z")
phase2_end_25 <- as_datetime("2025-12-01T23:59:59Z")

phase1_start_24 <- as_datetime("2024-08-01T00:00:00Z")
phase1_end_24 <- as_datetime("2024-10-17T00:00:00Z")
phase2_start_24 <- as_datetime("2024-10-17T18:16:00Z")
phase2_end_24 <- as_datetime("2024-10-28T00:00:00Z")

phase1_start_26 <- as_datetime("2026-09-01T00:00:00Z")
phase1_end_26 <- as_datetime("2026-10-12T00:00:00Z")

date_shift_24 <- phase1_start_26 - phase1_start_24
date_shift_25 <- phase1_start_26 - phase1_start_25

cum_24 <- here::here("media", "cumulative_registration_dc2024.csv") |>
  read_csv() |>
  add_row(
    registration_date = as_date(phase2_end_24),
    dc = year(as_date(phase2_end_24)),
    n = NULL
  ) |>
  fill(n, .direction = "down") |>
  mutate(
    registration_date = registration_date + date_shift_24,
    dc = as.integer(dc),
    n = as.integer(n),
    future = FALSE,
    NULL
  )

cum_25 <- here::here("media", "cumulative_registration_dc2025.csv") |>
  read_csv() |>
  mutate(
    registration_date = registration_date + date_shift_25,
    dc = as.integer(dc),
    n = as.integer(n),
    future = FALSE,
    NULL
  )

cum_26 <- prepare_cumulative_teams() |>
  mutate(
    dc = as.integer(dc),
    n = as.integer(n),
    NULL
  )

max_25 <- cum_25 |>
  slice(which.max(registration_date))
max_24 <- cum_24 |>
  slice(which.max(registration_date))
max_26 <- cum_26 |>
  slice(which.max(registration_date))

ggplot() +
  #---------- 2024 ---------
  geom_step(
    data = cum_24,
    aes(x = registration_date, y = n, linetype = future),
    colour = "#008000",
    alpha = 0.5,
    stat = "identity"
  ) +
  geom_text(
    data = max_24,
    aes(x = registration_date, y = n, label = n),
    size = 3,
    vjust = -0.5,
    colour = "#008000",
    alpha = 0.5
  ) +
  annotate(
    geom = "segment",
    x = as_date(phase2_end_24) + date_shift_24,
    y = 35,
    xend = as_date(phase2_end_24) + date_shift_24,
    yend = max_24 |> pull(n),
    arrow = arrow(length = unit(2, "mm")),
    colour = "#008000",
    alpha = 0.5
  ) +
  annotate(
    geom = "text",
    x = as_date(phase2_end_24) + date_shift_24 - ddays(8),
    y = 20,
    label = paste0(
      "End DC 2024\n  (",
      round(phase2_end_24 - phase1_start_24),
      " days)"
    ),
    size = 2.75,
    hjust = "left"
  ) +
  #---------- 2025 ---------
  geom_step(
    data = cum_25,
    aes(x = registration_date, y = n, linetype = future),
    colour = "blue",
    alpha = 0.5,
    stat = "identity"
  ) +
  geom_text(
    data = max_25,
    aes(x = registration_date, y = n, label = n),
    colour = "blue",
    alpha = 0.5,
    size = 3,
    vjust = -0.5
  ) +
  annotate(
    geom = "segment",
    x = as_date(phase2_end_25) + date_shift_25,
    y = 35,
    xend = as_date(phase2_end_25) + date_shift_25,
    yend = max_25 |> pull(n),
    arrow = arrow(length = unit(2, "mm")),
    colour = "blue",
    alpha = 0.5
  ) +
  annotate(
    geom = "text",
    x = as_date(phase2_end_25) + date_shift_25 - ddays(8),
    y = 20,
    label = paste0(
      "End DC 2025\n  (",
      round(phase2_end_25 - phase1_start_25),
      " days)"
    ),
    size = 2.75,
    hjust = "left"
  ) +
  #---------- 2026 ---------
  geom_step(
    data = cum_26,
    aes(x = registration_date, y = n, linetype = future),
    colour = "black",
    alpha = 0.5,
    stat = "identity"
  ) +
  geom_text(
    data = max_26,
    aes(x = registration_date, y = n, label = n),
    colour = "black",
    # size = 3,
    vjust = -0.5
  ) +
  annotate(
    geom = "segment",
    x = as_date(phase1_end_26),
    y = max_26 |> pull(n) - 90,
    xend = as_date(phase1_end_26),
    yend = max_26 |> pull(n),
    arrow = arrow(length = unit(2, "mm")),
    colour = "black",
    alpha = 0.5
  ) +
  annotate(
    geom = "text",
    x = as_date(phase1_end_26) - ddays(8),
    y = max_26 |> pull(n) - 100,
    label = paste0(
      "End DC 2026\n  (",
      round(phase1_end_26 - phase1_start_26),
      " days)"
    ),
    hjust = "left"
  ) +
  # metadata
  # annotate(
  #   geom = "text",
  #   x = as_date(phase1_end_26) - ddays(8),
  #   y = max_26 |> pull(n),
  #   label = paste0(
  #     "generated on ",
  #     stamp("2013-01-01T06:00:00Z")(now())
  #   ),
  #   hjust = "left"
  # ) +
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    # axis.text.x = element_blank(),
    # axis.ticks.x = element_blank(),
    legend.position = "none",
    NULL
  ) +
  labs(
    subtitle = paste0(
      "generated on ",
      lubridate::stamp("2013-01-01T06:00:00Z")(now())
    )
  )
```


```{r table-countries, eval=FALSE}
#| echo: false
#| warning: false
library(tidyverse)
library(ggplot2)
library(jsonlite)
library(here)
library(gt)


library(countrycode)

conflicts_prefer(dplyr::filter)

here("R", "helpers.R") |> source()

teams_raw <- get_teams_raw()

teams_valid <- teams_raw |> get_teams_valid()

members <- teams_raw |> get_teams_members()

ttt <- teams_valid |>
  mutate(registration_date = as_date(timestamp)) |>
  complete(
    registration_date = seq(ymd("2025-09-30"), ymd("2025-12-01"), by = "day")
  )

ccc <- teams_valid |>
  count(team_country) |>
  mutate(
    team_country = if_else(
      team_country == "Ireland {Republic}",
      "Ireland",
      team_country
    ),
    NULL
  ) |>
  mutate(
    iso3c = countrycode(team_country, 'country.name', 'iso3c')
  )


ccc |>
  dplyr::select(-iso3c) |>
  dplyr::arrange(desc(n), team_country) |>
  gt() |>
  cols_label(
    team_country = md("**Country**"),
    n = md("**# of teams**")
  )
```


```{r teams-bar-b2, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, eval=TRUE}
#| fig-cap: 'Teams per country'
library(countrycode)
library(scales)
library(here)
conflicts_prefer(dplyr::filter)

here("R", "helpers.R") |> source()

teams_raw <- get_teams_raw()
teams_valid <- teams_raw |> get_teams_valid()

teams_valid |>
  count(team_country) |>
  mutate(
    team_country = if_else(
      team_country == "Ireland {Republic}",
      "Ireland",
      team_country
    ),
    team_country = fct_reorder(team_country, n)
  ) |>
  ggplot() +
  geom_bar(aes(x = team_country, y = n), stat = "identity") +
  scale_y_continuous(
    breaks = breaks_pretty(),
    sec.axis = dup_axis(),
    expand = expansion(0)
  ) +
  coord_flip() +
  labs(y = "Number of teams") +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    # prism.ticks.length.y = unit(20, "pt"),
    # axis.ticks.length = unit(1, "cm"),
    NULL
  )
```


## Teams 
