
---
title: silly-xylophone
date: 2026-09-01
subtitle: Germany
acronyms:
  insert_loa: false
---

## Description and Rationale

We are a team of students with a strong interest in aviation, air traffic management, and data-driven analysis. We decided to register for the PRC Data Challenge to apply our analytical and technical skills to a real-world aviation problem and gain practical experience working with large-scale flight data. We are particularly interested in exploring the data, identifying meaningful patterns and operational insights, and developing a solution that can contribute to a better understanding of air traffic performance. The challenge also provides an excellent opportunity for us to learn, collaborate as a team, and work on a problem with real-world relevance to the aviation industry.

## Details

* Type: Academia
* Country: Germany

```{r echo=FALSE}
library(gt)

gt(tibble::tribble(
  ~id,      ~forename,                 ~surname,                         ~affiliation,
   1L,  "Dinesh Babu",            "Senguttuvan", "International school of management",
   2L, "Naresh Reddy", "Thogullapalli Ramreddy",                             "Unknow"
)
) |> cols_label(id = md("**ID**"), forename = md("**Forename**"), surname ~ md("**Surname**"), affiliation ~ md("**Affiliation**"))
```
