
---
title: trustworthy-zipper
date: 2026-09-10
subtitle: United Kingdom
acronyms:
  insert_loa: false
---

## Description and Rationale

We are a group of active University of Westminster students, ranging from undergraduate to postgraduate level, with backgrounds in Business Information Systems, Computer Science, and Data Science & Analytics.

As ambitious individuals, we decided to register for this challenge to apply and strengthen our skills through an exciting, hands-on project. The opportunity to work with open data, develop predictive analytics, share our work on GitHub, and publish an open-access paper provides valuable experience and exposure beyond lectures.

Through this challenge, we aim to develop both our technical and professional skills by applying what we have learned academically to a real-world problem. We are particularly excited to collaborate as a team, learn from one another, and explore predictive analytics in estimating the taxi-out time of flights across major European airports. We look forward to taking on this challenge and producing a meaningful, data-driven solution.

## Details

* Type: NA
* Country: United Kingdom
* Number of team members: 8

```{r echo=FALSE}
library(gt)

gt(tibble::tribble(
  ~id,       ~forename,    ~surname,                              ~affiliation,
   1L,         "Kabir",    "Ansari", "BSc Student - University of Westminster",
   2L,         "Harsh",  "Narendra", "BSc Student - University of Westminster",
   3L, "Mihai-Catalin",    "Vasile", "MSc Student - University of Westminster",
   4L,         "Oscar",    "Denche", "BSc Student - University of Westminster",
   5L,         "Maham",     "Baber", "BSc Student - University of Westminster",
   6L,         "Elisa", "Schezzini", "BSc Student - University of Westminster",
   7L,        "Kamran",    "Rzayev", "MSc Student - University of Westminster",
   8L,       "Anahita",   "Hessami", "MSc Student - University of Westminster"
)
) |> cols_label(id = md("**ID**"), forename = md("**Forename**"), surname ~ md("**Surname**"), affiliation ~ md("**Affiliation**"))
```
