---
title: Eligibility
acronyms:
  insert_loa: false
---

::: {.callout-note title="Please note"}
We have made every effort to ensure that the registration process complies with
the applicable eligibility rules.
However, we reserve the right to refuse/stop participation of teams from
countries/companies subject to restrictions at any stage of the challenge. 
:::

## Eligibility for participation

Participation is open to teams worldwide, subject to applicable sanctions and
restrictions.

Restrictions apply to teams originating from, or affiliated with, institutions
or companies in countries that are either not EUROCONTROL Member States or
Comprehensive Agreement States, or are subject to sanctions. 

Regardless of the reason for the sanctions, these restrictions are also in place
because of the practical difficulties involved in transferring prize money to
winning teams based in these countries. 

The registration form implements these restrictions as far as possible.

Please refer to the [EU Sanctions Map](https://www.sanctionsmap.eu/) and to the
[EUROCONTROL Member and Comprehensive Agreement States](https://www.eurocontrol.int/our-member-and-comprehensive-agreement-states)
for the list of EUROCONTROL states.


## Eligibility for Prize

The winning submissions/solutions will only be eligible for the awards if:

* The team is NOT related in any way to sanctioned non-EUROCONTROL states. See above.
* All used external datasets are openly accessible/usable and documented.
* All produced **source code** are made openly available on GitHub under the **GNU GPLv3 license**. Note: It will then be forked by the Challenge GitHub account for organisational purposes.
* All **additional datasets** used are openly available under an open source license.
* Sufficient **documentation** is provided **to understand and reproduce** the results.
* The solution is **_original_**: Teams must use their own original solutions.
  Re-using any existing implementation is only allowed if the original authors 
  grant you the rights to use their solution and if you made significant
  modifications to the algorithm or model. In particular, simply re-using existing code and rewriting the data input and output mechanism is not sufficient. Adding parameters to the model and modifying filters to match the specific peculiarities of the data, however, can be considered sufficient. 
